remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: [Welome to Software Engineering Made Simple]
description: [In the age of AI0x2C cloud0x2C and big data0x2C the principles of good software engineering are more important than ever]